name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill in as much detail as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear description of the observed behavior
      placeholder: Explain the bug
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Exact commands or steps to reproduce
      placeholder: |
        1. Run ...
        2. Use flags ...
        3. Observe error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should happen instead?
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/output
      render: shell

